server:
    port: ${PORT:9000}

app:
  version: 1.0.19


spring:
  datasource:
    url: jdbc:mysql://localhost/test2?useSSL=false
    username: root
    password: 123456789
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create